In [2]:
import numpy as np
import tensorflow as tf

# 1. Define the input matrix (5x5)
input_matrix = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
], dtype=np.float32)

# 2. Define the kernel (3x3)
kernel = np.array([
    [0, 1, 0],
    [1, -4, 1],
    [0, 1, 0]
], dtype=np.float32)

# Reshape input and kernel to match TensorFlow format
# TensorFlow expects: input [batch, height, width, channels], kernel [height, width, in_channels, out_channels]
input_tensor = tf.constant(input_matrix.reshape(1, 5, 5, 1))
kernel_tensor = tf.constant(kernel.reshape(3, 3, 1, 1))

# 3. Define convolution function
def apply_convolution(stride, padding):
    output = tf.nn.conv2d(input_tensor, kernel_tensor, strides=[1, stride, stride, 1], padding=padding)
    return tf.squeeze(output).numpy()  # remove dimensions of size 1 for easier viewing

# 4. Apply convolutions with different parameters and print results
configs = [
    (1, 'VALID'),
    (1, 'SAME'),
    (2, 'VALID'),
    (2, 'SAME')
]

for stride, padding in configs:
    result = apply_convolution(stride, padding)
    print(f"\nStride = {stride}, Padding = '{padding}'\n", result)



Stride = 1, Padding = 'VALID'
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Stride = 1, Padding = 'SAME'
 [[  4.   3.   2.   1.  -6.]
 [ -5.   0.   0.   0. -11.]
 [-10.   0.   0.   0. -16.]
 [-15.   0.   0.   0. -21.]
 [-46. -27. -28. -29. -56.]]

Stride = 2, Padding = 'VALID'
 [[0. 0.]
 [0. 0.]]

Stride = 2, Padding = 'SAME'
 [[  4.   2.  -6.]
 [-10.   0. -16.]
 [-46. -28. -56.]]
